jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean -B package -Prelease --file pom.xml
    - continue-on-error: true
      env:
        IMAGE_LOAD: true
        IMAGE_PLATFORM: linux/amd64
        IMAGE_PUSH: false
      name: Build Image
      run: 'docker buildx create --use --name myBuilder --driver docker-container

        docker buildx use myBuilder


        ./script/docker/server/build.sh

        '
    - continue-on-error: true
      name: Run E2E
      run: 'sudo curl -L https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        -o /usr/local/bin/docker-compose

        sudo chmod u+x /usr/local/bin/docker-compose


        cd e2e && ./start.sh

        '
name: Backend CI
on:
  repository_dispatch:
    types: trigger-ga___backend-build-test.yml
