jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install Prince
      run: 'LANG="zh_CN.UTF-8"

        export LANG="zh_CN.UTF-8"

        curl https://www.princexml.com/download/prince-15.1-macos.zip -O

        tar zxf prince-15.1-macos.zip

        cd prince-15.1-macos

        yes "" | sudo ./install.sh

        '
    - continue-on-error: true
      name: Build CN PDF
      run: npx docusaurus-prince-pdf -u https://hertzbeat.apache.org/zh-cn/docs --output
        docs-cn.pdf
    - continue-on-error: true
      name: Build EN PDF
      run: npx docusaurus-prince-pdf -u https://hertzbeat.apache.org/docs --output
        docs-en.pdf
    - continue-on-error: true
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: docs-cn-pdf
        path: docs-cn.pdf
        retention-days: 1
    - continue-on-error: true
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: docs-en-pdf
        path: docs-en.pdf
        retention-days: 1
name: HertzBeat Doc Pdf Builder
on:
  repository_dispatch:
    types: trigger-ga___doc-pdf-builder.yml
