jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Yarn Install
      run: yarn
      working-directory: web-app
    - continue-on-error: true
      name: EsLint Test
      run: yarn lint:ts
      working-directory: web-app
name: Frontend CI
on:
  repository_dispatch:
    types: trigger-ga___frontend-build-test.yml
