jobs:
  check-license-header:
    name: check-license-header
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Check license header
      uses: apache/skywalking-eyes@v0.6.0
    timeout-minutes: 10
name: License Checker
on:
  repository_dispatch:
    types: trigger-ga___license-checker.yml
