jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Label pull request
      uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
name: Pull Request Robot
on:
  repository_dispatch:
    types: trigger-ga___pull-request-robot.yml
